Inner color branch
cocoatoucher/AIFlatSwitch pull request #18
Opened 2019-03-17 18:45 UTC by Maryom

2019-03-18 14:42 UTC, cocoatoucher requested changes

2019-03-18 14:42 UTC, cocoatoucher commented on Source/AIFlatSwitch.swift
> +            self.backgroundLayer.backgroundColor = backgroundLayerColor.cgColor
This should be self.backgroundLayer.fillColor instead

2019-03-18 14:42 UTC, cocoatoucher commented on Source/AIFlatSwitch.swift
> +        backgroundLayer.backgroundColor = backgroundLayerColor.cgColor
Same here, it should be backgroundLayer.fillColor, not backgroundColor

2019-03-18 14:43 UTC, cocoatoucher commented
Hey, there is just a small error, you should use fillColor on layers instead of backgroundColor
Thanks very much for all the changes you made :)

2019-03-18 14:45 UTC, Maryom commented
Most welcome :) I will fix them ASAP

2019-03-22 13:33 UTC, merged

2019-03-22 13:34 UTC, cocoatoucher commented
Thank you very much!

2019-03-22 15:34 UTC, Maryom commented
Most welcome